version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
      timezone: Asia/Kolkata
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Asia/Kolkata
    groups:
      github-actions:
        patterns: ["*"]
