// Generated by scripts/generate-blog-index.ts. Do not edit by hand.
export const blogIndex = [
  {
    slug: "home-loan-balance-transfer-math",
    title: "Home loan balance transfer: when switching actually saves money",
    date: "2026-07-09",
    excerpt:
      "A lower rate isn't automatically a better deal. The honest arithmetic of balance transfers — fees, resets and the one variable everyone forgets.",
    tag: "Home Loans",
    author: "TrueLend Advisory Desk",
  },
  {
    slug: "personal-loan-vs-credit-card",
    title: "Personal loan vs credit card: the real cost of convenient money",
    date: "2026-07-12",
    excerpt:
      "Both put money in your hands this week. One costs three times the other. How to choose between a personal loan, card EMI, and revolving credit.",
    tag: "Personal Finance",
    author: "TrueLend Advisory Desk",
  },
  {
    slug: "why-750-is-the-magic-cibil-number",
    title: "Why 750 is the magic CIBIL number — and how to get there",
    date: "2026-07-06",
    excerpt:
      "Lenders don't read your credit report the way you do. Here's what actually happens above and below the 750 line, and the six-month plan to cross it.",
    tag: "Credit Score",
    author: "TrueLend Advisory Desk",
  },
] as const;
