import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";
import { format } from "prettier";
import { z } from "zod";

const frontmatterSchema = z.object({
  title: z.string().min(1),
  date: z.coerce.date(),
  excerpt: z.string().min(1),
  tag: z.string().min(1),
  author: z.string().default("TrueLend Advisory Desk"),
});

const contentDirectory = path.join(process.cwd(), "content/blog");
const posts = fs
  .readdirSync(contentDirectory)
  .filter((file) => file.endsWith(".mdx"))
  .sort()
  .map((file) => {
    const { data } = matter(fs.readFileSync(path.join(contentDirectory, file), "utf8"));
    const parsed = frontmatterSchema.parse(data);
    return {
      slug: file.replace(/\.mdx$/, ""),
      ...parsed,
      date: parsed.date.toISOString().slice(0, 10),
    };
  });

const output = `// Generated by scripts/generate-blog-index.ts. Do not edit by hand.\nexport const blogIndex = ${JSON.stringify(posts, null, 2)} as const;\n`;
const outputPath = path.join(process.cwd(), "content/blog-index.ts");
const formatted = await format(output, { filepath: outputPath });

if (process.argv.includes("--check")) {
  const current = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, "utf8") : "";
  if (current !== formatted) {
    console.error("content/blog-index.ts is stale; run pnpm generate:blog and commit the result");
    process.exitCode = 1;
  }
} else {
  fs.writeFileSync(outputPath, formatted);
}
